name: "WP Media PR Checklist Action"
description: "A GitHub action that performs checks on PR descriptions, according to WP Media PR template"
inputs:
  repo-token:
    description: "The PR_CHECKLIST_TOKEN secret token with read access to Pull Requests."
    required: true
runs:
  using: "node20"
  main: "dist/index.js"